services:
  pf:
    build:
      context: ../pf
      target: deploy
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../pf/.env.development
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=silver
      - POSTGRES_PASSWORD=thisisalocalnetworkserver
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Doesn't work Lol i cant be bothered
  #  prisma-studio:
  #    container_name: prisma-studio
  #    ports:
  #      - "5555:5555"
  #    build:
  #      context: pf
  #      dockerfile: dev.prod.Dockerfile-prisma-studio
  #    depends_on:
  #      - db

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ../proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - pf

volumes:
  db-data: { }
