services:
  pf:
    build:
      dockerfile: prod.Dockerfile
    env_file:
      - ../pf/.env.production
    # don't do none of that host volume mapping business
    volumes: !reset []

  api:
    build:
      dockerfile: prod.Dockerfile
    # don't do none of that host volume mapping business
    volumes: !reset [ ]
